# Generated by Django 3.2.16 on 2023-09-21 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^(\\+7|8)[0-9]{10}$', "Введите номер телефона в формате: '+79995553322'")]),
        ),
    ]
