@service = http://127.0.0.1:8000/api/v1/autoservice/service/
@company = http://127.0.0.1:8000/api/v1/autoservice/company/
@service_id = http://127.0.0.1:8000/api/v1/autoservice/service/1/
@filter_service = http://127.0.0.1:8000/api/v1/autoservice/service/?latitude=60&longitude=60
@feedback = http://127.0.0.1:8000/api/v1/autoservice/service/1/feedback/
@feedback_id = http://127.0.0.1:8000/api/v1/autoservice/service/1/feedback/1/
@create_user = http://127.0.0.1:8000/api/v1/auth/users/

###
GET {{ service }} HTTP/1.1
content-type: application/json

###
GET {{ company }} HTTP/1.1
content-type: application/json

###
GET {{ service_id }} HTTP/1.1
content-type: application/json

###
GET {{ filter_service }} HTTP/1.1
content-type: application/json

###
GET {{ feedback }} HTTP/1.1
content-type: application/json

###
GET {{ feedback_id }} HTTP/1.1
content-type: application/json

###
POST {{ get_user_token }} HTTP/1.1
content-type: application/json

{
    "username": "ap",
    "password": "qwe123"
}

###
POST {{ get_user_token }} HTTP/1.1
content-type: application/json

{
    "username": "apap",
    "password": "qweqwe"
}

###
POST {{ feedback }} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk2NDg2MTMxLCJqdGkiOiI3MzEyNTFmMTAxZWU0MmNiYWUxMjI3MWU2NGI5ODc4ZiIsInVzZXJfaWQiOjJ9.BCHCgZ9GegEqiRnMkDhEQYuxTZ2p2tvmA4EKzv0Ubms

{
    "text": "Все круто, мастер в прямом смысле облизывал машину, немного странно но прикольно",
    "score": 5
}

###
POST {{ create_user }} HTTP/1.1
Content-Type: application/json

{
  "email": "user@example.com",
  "first_name": "string",
  "password": "qwe123"
}