@service = http://127.0.0.1:8000/api/v1/autoservice/service/
@service_id = http://127.0.0.1:8000/api/v1/autoservice/service/11/
@filter_service = http://127.0.0.1:8000/api/v1/autoservice/service/?latitude=60&longitude=60
@feedback = http://127.0.0.1:8000/api/v1/autoservice/service/2/feedback/

###
GET {{ service }} HTTP/1.1
content-type: application/json

###
GET {{ service_id }} HTTP/1.1
content-type: application/json

###
GET {{ filter_service }} HTTP/1.1
content-type: application/json

###
GET {{ feedback }} HTTP/1.1
content-type: application/json

###
POST {{ feedback }} HTTP/1.1
content-type: application/json

{
    "text": "Хрнеь какая то",
    "score": 1
}
