# Generated by Django 3.2.16 on 2023-09-28 05:36

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150, verbose_name='Название бренда')),
                ('slug', models.CharField(max_length=150, verbose_name='Уникальный Slug')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('brand',),
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет автомобиля')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN-номер автомобиля')),
                ('number_of_car', models.CharField(max_length=9, verbose_name='Гос.номер автомобиля')),
                ('odometr', models.CharField(max_length=10, verbose_name='Пробег автомобиля')),
                ('year', models.PositiveIntegerField(verbose_name='Год приобретения автомобиля')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transport', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ('-id',),
            },
        ),
    ]
