# Generated by Django 3.2.16 on 2023-09-16 17:57

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет автомобиля')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN-номер автомобиля')),
                ('number_of_car', models.CharField(max_length=9, verbose_name='Гос.номер автомобиля')),
                ('odometr', models.CharField(max_length=10, verbose_name='Пробег автомобиля')),
                ('year', models.PositiveIntegerField(verbose_name='Год приобретения автомобиля')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150, verbose_name='Название бренда')),
                ('model', models.CharField(max_length=150, verbose_name='Название модели')),
                ('image', models.ImageField(upload_to='transports/', verbose_name='Изображение автомобиля')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорты',
                'ordering': ('brand',),
            },
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.UniqueConstraint(fields=('brand', 'model'), name='unique_transport'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transport', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='cars',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
