# Generated by Django 3.2.16 on 2023-09-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ('brand',), 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.RemoveConstraint(
            model_name='transport',
            name='unique_transport',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='image',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='model',
        ),
        migrations.AddField(
            model_name='transport',
            name='slug',
            field=models.CharField(default=1, max_length=150, verbose_name='Уникальный Slug'),
            preserve_default=False,
        ),
    ]
