# Generated by Django 3.2.16 on 2023-09-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название компании', max_length=250, verbose_name='Название компании по ремонту')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('slug', models.SlugField()),
                ('legal_address', models.CharField(max_length=250, verbose_name='Юридический адрес')),
            ],
            options={
                'verbose_name': 'Компания по ремонту авто',
                'verbose_name_plural': 'Компания по ремонту авто',
            },
        ),
        migrations.CreateModel(
            name='AutoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Укажите адрес автосервиса', max_length=250, verbose_name='Адрес автосервиса')),
                ('latitude', models.FloatField(verbose_name='Значение северной широты на карте')),
                ('longitude', models.FloatField(verbose_name='Значение восточной долготы на карте')),
                ('company', models.ForeignKey(help_text='Выберите компанию', on_delete=django.db.models.deletion.CASCADE, to='autoservice.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Автосервис',
                'verbose_name_plural': 'Автосервис',
            },
        ),
    ]
