# Generated by Django 3.2.16 on 2023-09-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoservice',
            name='openfrom',
            field=models.CharField(help_text='Введите время начала рабочего дня автосервиса в формате HH:MM', max_length=5, null=True, verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='openuntil',
            field=models.CharField(help_text='Введите время окончания рабочего дня автосервиса в формате HH:MM', max_length=5, null=True, verbose_name='Окончание рабочего дня'),
        ),
    ]
