# Generated by Django 3.2.16 on 2023-09-28 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoservice',
            name='car_service',
            field=models.ManyToManyField(help_text='Выберите автомобильные бренды', related_name='autoservices', to='cars.Transport', verbose_name='Автомобильные бренды'),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='city',
            field=models.ForeignKey(help_text='Укажите город', on_delete=django.db.models.deletion.CASCADE, to='autoservice.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='company',
            field=models.ForeignKey(help_text='Выберите компанию', on_delete=django.db.models.deletion.CASCADE, to='autoservice.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='geolocation',
            field=models.ForeignKey(help_text='Укажите геолокацию автосервиса', on_delete=django.db.models.deletion.CASCADE, to='autoservice.geolocationautoservice', verbose_name='Геолокация автосервиса'),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='job',
            field=models.ManyToManyField(help_text='Выберите необходимый тип работ', through='autoservice.AutoserviceJob', to='autoservice.Job', verbose_name='Работы'),
        ),
    ]
