# Generated by Django 3.2.16 on 2023-09-19 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_auto_20230919_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoservice',
            name='site',
            field=models.CharField(default='www.qwe.com', help_text="Введите адрес сайта автосервиса в формате 'www.example.com'", max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^(https?|ftp)://[^\\s/$.?#].[^\\s]*$$', message="Ошибка ввода, используйте формат: 'www.example.com'")], verbose_name='Сайт автосервиса'),
            preserve_default=False,
        ),
    ]
