# Generated by Django 3.2.16 on 2023-09-20 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_autoservice_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoservice',
            name='openfrom',
            field=models.CharField(help_text='Введите время начала рабочего дня автосервиса в формате HH:MM', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^(?:[01]\\d|2[0-3]):[0-5]\\d$', 'Используйте время в формате HH:MM')], verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='openuntil',
            field=models.CharField(help_text='Введите время окончания рабочего дня автосервиса в формате HH:MM', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^(?:[01]\\d|2[0-3]):[0-5]\\d$', 'Используйте время в формате HH:MM')], verbose_name='Окончание рабочего дня'),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^(\\+7|8)[0-9]{10}$', "Введите номер телефона в формате: '+79995553322'")]),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='site',
            field=models.CharField(help_text="Введите адрес сайта автосервиса в формате 'www.example.com'", max_length=80, unique=True, verbose_name='Сайт автосервиса'),
        ),
    ]
