# Generated by Django 3.2.16 on 2023-09-21 06:10

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_auto_20230920_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoservice',
            name='email',
            field=models.EmailField(help_text='Введите адрес электронной почты', max_length=80, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона', max_length=12, validators=[django.core.validators.RegexValidator('^(\\+7|8)[0-9]{10}$', "Введите номер телефона в формате: '+79995553322'")]),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='site',
            field=models.CharField(help_text="Введите адрес сайта автосервиса в формате 'www.example.com'", max_length=80, verbose_name='Сайт автосервиса'),
        ),
        migrations.AlterField(
            model_name='autoservicejob',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='Стоимость ниже 1 невозможна')], verbose_name='Стоимость работ'),
        ),
    ]
