# Generated by Django 3.2.16 on 2023-09-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_feedback'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='geolocationautoservice',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_geoservice'),
        ),
        migrations.AddConstraint(
            model_name='geolocationcity',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_city'),
        ),
    ]
