# Generated by Django 3.2.16 on 2023-09-22 19:48

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_auto_20230921_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoservice',
            name='email',
            field=models.EmailField(help_text='Введите адрес электронной почты', max_length=80, null=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='site',
            field=models.CharField(help_text="Введите адрес сайта автосервиса в формате 'www.example.com'", max_length=80, null=True, verbose_name='Сайт автосервиса'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_address',
            field=models.CharField(max_length=250, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='autoservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='autoservice.autoservice', verbose_name='Автосервис'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=150, null=True, verbose_name='Описание работы'),
        ),
    ]
