# Generated by Django 3.2.16 on 2023-09-22 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0009_auto_20230922_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoservice',
            name='holidays',
            field=models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], help_text='Укажите выходной день', max_length=1, null=True, verbose_name='Выходной день'),
        ),
        migrations.AlterField(
            model_name='autoservice',
            name='phone_number',
            field=models.CharField(help_text='Введите номер телефона', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^(\\+7|8)[0-9]{10}$', "Введите номер телефона в формате: '+79995553322'")]),
        ),
    ]
